Add user activation, metadata, routes, and soft delete logic; fix response path and server errors
ISIL-ESTE/Student-Workflow-Organizer pull request #56
Opened 2023-06-26 16:38 UTC by bellaabdelouahab

related issues #54 #22 

here effected tasks in general 

- [x] Add activation requirement for new signup users (optional via env).
- [X] Add metadata fields: deleted, updatedBy, createdBy, deletedBy, deletedAt.
- [X] Implement routes: activate, updateMyPassword, forgotPassword.
- [X] Add soft delete logic (requires extensive testing).
- [X] Fix server errors displayed on production environment.

@yassineboujrada @Khalid1G @muttaqin1 
please provide some feedbacks

2023-06-26 18:06 UTC, muttaqin1 requested changes

2023-06-26 18:06 UTC, muttaqin1 commented on backend-app/controllers/auth_controller.js
> +    if (!resetKey) {
This status code can be 400

2023-06-26 18:06 UTC, muttaqin1 commented on backend-app/controllers/auth_controller.js
> +    if (resetKey !== user.resetKey) {
This status code can be 403

2023-06-26 18:06 UTC, muttaqin1 commented on backend-app/controllers/auth_controller.js
> +    if (!email) {
This status code can be 400

2023-06-26 18:11 UTC, muttaqin1 approved these changes
All seems fine.

2023-06-26 18:12 UTC, Khalid1G approved these changes

2023-06-26 18:51 UTC, bellaabdelouahab commented on backend-app/controllers/auth_controller.js
> +    if (!email) {
sure

2023-06-26 18:52 UTC, bellaabdelouahab commented on backend-app/app.js
> +  const err = new AppError(404, 'fail', 'Route Not Found', req.originalUrl);
sure

2023-06-26 18:53 UTC, bellaabdelouahab commented on backend-app/constants/meta_data.js
> +        deletedBy: {
and how we should handle system ?

2023-06-26 18:57 UTC, bellaabdelouahab commented on backend-app/middlewares/global_error_handler.js
> +      description:
what do you mean this is the most optimized way, I think it needs just some comments
give an example of what is hard to read

2023-06-26 19:11 UTC, Khalid1G commented on backend-app/constants/meta_data.js
> +        deletedBy: {
create account system and put that ID

2023-06-26 19:47 UTC, bellaabdelouahab commented on backend-app/middlewares/global_error_handler.js
> +      description:
sure i ll fix it in next pr

2023-06-27 16:39 UTC, muttaqin1 approved these changes
great👌

2023-06-27 16:53 UTC, bellaabdelouahab commented on backend-app/constants/meta_data.js
> +        deletedBy: {
no the right way

2023-06-27 16:54 UTC, bellaabdelouahab commented on backend-app/controllers/auth_controller.js
> +    if (resetKey !== user.resetKey) {
👌

2023-06-28 09:33 UTC, bellaabdelouahab commented
@Khalid1G

2023-07-01 15:20 UTC, merged