Feat/token-based-authentication
ISIL-ESTE/Student-Workflow-Organizer pull request #75
Opened 2023-07-25 13:29 UTC by muttaqin1

1- **Generate tokens.**
2- **Save tokens in db.**
2 **Configure eslint & prettier.** 

Partially resolved issue #46

2023-07-25 13:57 UTC, bellaabdelouahab requested changes
here is some review on your pr , all tho I'm not sure if you tested this with e2e test

2023-07-25 13:57 UTC, bellaabdelouahab commented on backend-app/package.json
>    }
can you quickly  use specified version instead of ^ because it may cause a different in the future

2023-07-25 13:57 UTC, bellaabdelouahab commented on backend-app/config/app_config.js
> +exports.ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET || 'sdfsdf';
I might have to resolve this because it conflicts with my pr

2023-07-25 18:34 UTC, bellaabdelouahab approved these changes

2023-07-25 18:37 UTC, bellaabdelouahab approved these changes

2023-07-25 18:38 UTC, merged

2023-07-25 18:47 UTC, muttaqin1 commented
I will add the token refresh and logout controller soon.

2023-07-25 18:49 UTC, bellaabdelouahab commented
wait but why the refresh token is the same as access token
@muttaqin1

2023-07-25 18:53 UTC, muttaqin1 commented
> wait but why the refresh token is the same as access token
> @muttaqin1 

where? 
The base64uri encoded strings are kinda identical to one another.
@bellaabdelouahab

2023-07-25 18:56 UTC, muttaqin1 commented
ooh😂😂,
 The header payload and secret for the access & refresh token are same.

```js
exports.ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET || 'sdfsdf';
exports.ACCESS_TOKEN_EXPIRY_TIME = process.env.ACCESS_TOKEN_EXPIRY_TIME || '1d';
exports.REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET || 'sdfsdf';
exports.REFRESH_TOKEN_EXPIRY_TIME = process.env.REFRESH_TOKEN_EXPIRY_TIME || '1d';

```
@bellaabdelouahab

2023-07-26 16:57 UTC, bellaabdelouahab commented
> ooh😂😂, The header payload and secret for the access & refresh token are same.
> 
> ```js
> exports.ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET || 'sdfsdf';
> exports.ACCESS_TOKEN_EXPIRY_TIME = process.env.ACCESS_TOKEN_EXPIRY_TIME || '1d';
> exports.REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET || 'sdfsdf';
> exports.REFRESH_TOKEN_EXPIRY_TIME = process.env.REFRESH_TOKEN_EXPIRY_TIME || '1d';
> ```
> 
> @bellaabdelouahab

i think you missed this :


![image](https://github.com/ISIL-ESTE/Student-Workflow-Organizer/assets/81409194/07be73f4-4ec7-4638-acc8-dbe55570a3b8)

jwt env variable already exist , should i remove the duplicated value ?
@muttaqin1

2023-07-26 18:08 UTC, muttaqin1 commented
yes.
Sorry,  i haven’t noticed that.
@bellaabdelouahab